Name - Maahi Ankit Sadrani
PRN - 25070123069

In [ ]:
# Experiment 14 - Data Binning And Data Formatting using python

In [1]:
import pandas as pd
import numpy as np

data = {
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price' : [55000,20000,30000,2000,8000,45000],
    'Units_sold':[25,60,35,80,50,15]
}
df = pd.DataFrame(data)
df

      Product  Price  Units_sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [2]:
# Data Binning
bins1 = [0,10000,30000,60000]
labels1 = ['Low','Medium','High']

df['Price_category'] = pd.cut(df['Price'],bins=bins1,labels=labels1)
df

      Product  Price  Units_sold Price_category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [3]:
# Binning Units Sold
bins2 = [0,30,60,100]
labels2 = ['Low Sales','Medium Sales','High Sales']

df['Sales_category'] = pd.cut(df['Units_sold'],bins=bins2,labels=labels2)
df

      Product  Price  Units_sold Price_category Sales_category
0      Laptop  55000          25           High      Low Sales
1      Mobile  20000          60         Medium   Medium Sales
2      Tablet  30000          35         Medium   Medium Sales
3  Headphones   2000          80            Low     High Sales
4  Smartwatch   8000          50            Low   Medium Sales
5      Camera  45000          15           High      Low Sales

In [5]:
# Data formating:
# Convert Data type

print(df.dtypes)
df['Units_sold'] = df['Units_sold'].astype(float)
print(df.dtypes)

Product             object
Price                int64
Units_sold           int64
Price_category    category
Sales_category    category
dtype: object
Product             object
Price                int64
Units_sold         float64
Price_category    category
Sales_category    category
dtype: object

In [7]:
# Convert Text to upercase
df['Product'] = df['Product'].str.upper()
df

      Product  Price  Units_sold Price_category Sales_category
0      LAPTOP  55000        25.0           High      Low Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales

In [9]:
# Rounding Values
df['Price'] = df['Price'].round(2)
df

      Product  Price  Units_sold Price_category Sales_category
0      LAPTOP  55000        25.0           High      Low Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales

In [14]:
# Additional
# Sort Data
sorted_df = df.sort_values(by ='Price')
print(sorted_df)

      Product  Price  Units_sold Price_category Sales_category
3  HEADPHONES   2000        80.0            Low     High Sales
4  SMARTWATCH   8000        50.0            Low   Medium Sales
1      MOBILE  20000        60.0         Medium   Medium Sales
2      TABLET  30000        35.0         Medium   Medium Sales
5      CAMERA  45000        15.0           High      Low Sales
0      LAPTOP  55000        25.0           High      Low Sales

In [16]:
# Display Unique Values
print(df['Price_category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [17]:
# Dataset: Food Delivery orders
import pandas as pd
import numpy as np

data = {
    'Order_ID':['01','02','03','04','05','06','07','08'],
    'Order_Value' : [250,450, 120, 600, 300, 150, 500, 220],
    'Delivery_Time' : [30,45,25, 60, 35, 20, 50, 28],
     'Distance_km' : [5,8,3,10,6,2,9,4]
}
df = pd.DataFrame(data)
df

  Order_ID  Order_Value  Delivery_Time  Distance_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [18]:
# Binning Order Values

bins = [0,200,400,700]
labels = ['Low order','Medium order','High order']

df['Order_category'] = pd.cut(df['Order_Value'],bins=bins,labels=labels)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_category
0       01          250             30            5   Medium order
1       02          450             45            8     High order
2       03          120             25            3      Low order
3       04          600             60           10     High order
4       05          300             35            6   Medium order
5       06          150             20            2      Low order
6       07          500             50            9     High order
7       08          220             28            4   Medium order

In [20]:
# Binning Delivery time
bins2 = [0,30,45,60]
labels2 = ['Fast Delivery','Average Delivery','Slow Delivery']
df['Delivery_Time'] = pd.cut(df['Delivery_Time'], bins=bins2, labels=labels2)
print(df)

  Order_ID  Order_Value     Delivery_Time  Distance_km Order_category
0       01          250     Fast Delivery            5   Medium order
1       02          450  Average Delivery            8     High order
2       03          120     Fast Delivery            3      Low order
3       04          600     Slow Delivery           10     High order
4       05          300  Average Delivery            6   Medium order
5       06          150     Fast Delivery            2      Low order
6       07          500     Slow Delivery            9     High order
7       08          220     Fast Delivery            4   Medium order

In [24]:
# Binning kilometer
bins3 = [0,5,8,10]
labels3 = ['Near','Medium','Far']
df['Distance_category'] = pd.cut(df['Distance_km'], bins=bins3, labels=labels3)
print(df)

  Order_ID  Order_Value     Delivery_Time  Distance_km Order_category  \
0       01          250     Fast Delivery            5   Medium order
1       02          450  Average Delivery            8     High order
2       03          120     Fast Delivery            3      Low order
3       04          600     Slow Delivery           10     High order
4       05          300  Average Delivery            6   Medium order
5       06          150     Fast Delivery            2      Low order
6       07          500     Slow Delivery            9     High order
7       08          220     Fast Delivery            4   Medium order

  Distance_category Distance
0              Near     Near
1            Medium   Medium
2              Near     Near
3               Far      Far
4            Medium   Medium
5              Near     Near
6               Far      Far
7              Near     Near

In [26]:
# Data formating:
# Convert Data type

print(df.dtypes)
df['Distance_km'] = df['Distance_km'].astype(float)
print(df.dtypes)

Order_ID               object
Order_Value             int64
Delivery_Time        category
Distance_km             int64
Order_category       category
Distance_category    category
Distance             category
dtype: object
Order_ID               object
Order_Value             int64
Delivery_Time        category
Distance_km           float64
Order_category       category
Distance_category    category
Distance             category
dtype: object

In [25]:
# Count of categories
print(df['Order_category'].value_counts())
df

Order_category
Medium order    3
High order      3
Low order       2
Name: count, dtype: int64

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_category,Distance_category,Distance
0,01,250,Fast Delivery,5,Medium order,Near,Near
1,02,450,Average Delivery,8,High order,Medium,Medium
2,03,120,Fast Delivery,3,Low order,Near,Near
3,04,600,Slow Delivery,10,High order,Far,Far
4,05,300,Average Delivery,6,Medium order,Medium,Medium
5,06,150,Fast Delivery,2,Low order,Near,Near
6,07,500,Slow Delivery,9,High order,Far,Far
7,08,220,Fast Delivery,4,Medium order,Near,Near

In [27]:
# Sort Data
sorted_df = df.sort_values(by ='Order_Value')
print(sorted_df)

  Order_ID  Order_Value     Delivery_Time  Distance_km Order_category  \
2       03          120     Fast Delivery          3.0      Low order
5       06          150     Fast Delivery          2.0      Low order
7       08          220     Fast Delivery          4.0   Medium order
0       01          250     Fast Delivery          5.0   Medium order
4       05          300  Average Delivery          6.0   Medium order
1       02          450  Average Delivery          8.0     High order
6       07          500     Slow Delivery          9.0     High order
3       04          600     Slow Delivery         10.0     High order

  Distance_category Distance
2              Near     Near
5              Near     Near
7              Near     Near
0              Near     Near
4            Medium   Medium
1            Medium   Medium
6               Far      Far
3               Far      Far

In [28]:
# Convert Text to upercase
df['Distance_category'] = df['Distance_category'].str.upper()
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_category,Distance_category,Distance
0,01,250,Fast Delivery,5.0,Medium order,NEAR,Near
1,02,450,Average Delivery,8.0,High order,MEDIUM,Medium
2,03,120,Fast Delivery,3.0,Low order,NEAR,Near
3,04,600,Slow Delivery,10.0,High order,FAR,Far
4,05,300,Average Delivery,6.0,Medium order,MEDIUM,Medium
5,06,150,Fast Delivery,2.0,Low order,NEAR,Near
6,07,500,Slow Delivery,9.0,High order,FAR,Far
7,08,220,Fast Delivery,4.0,Medium order,NEAR,Near